export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS"
export const FETCH_PROJECTS_FAILED = "FETCH_PROJECTS_FAILED"
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAILED = "ADD_PROJECT_SUCCESS"
export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECTS = "GET_PROJECTS";
export const FETCH_PROJECT_FAILED = "FETCH_PROJECT_FAILED,"
export const GET_PROJECT = "GET_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";


export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILED = "ADD_TASK_FAILED";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILED = "DELETE_TASK_FAILED"
export const GET_BACKLOG = "GET_BACKLOG";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
export const FETCH_ALLPROJECT_TASKS_SUCCESS = "FETCH_ALLPROJECT_TASKS_SUCCESS"
export const FETCH_ALLPROJECT_TASKS_FAILED = "FETCH_ALLPROJECT_TASKS_FAILED"
export const DELETE_TASK_BYID_SUCCESS = "DELETE_TASK_BYID_SUCCESS"
export const ADD_TASK_SUCCESS_BUTTON = " ADD_TASK_SUCCESS_BUTTON"
export const ADD_TASK_FAILED_BUTTON = "ADD_TASK_FAILED_BUTTON"


export const FETCH_EXPENSE_SUCCESS = "FETCH_EXPENSE_SUCCES";
export const FETCH_EXPENSE_FAILED = "FETCH_EXPENSE_FAILED";
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS";
export const ADD_EXPENSE_FAILED = "ADD_EXPENSE_FAILED";
export const DELETE_EXPENSE_SUCCESS = "DELETE_EXPENSE_SUCCESS";
export const DELETE_EXPENSE_FAILED = "DELETE_EXPENSE_FAILED";
export const UPDATE_EXPENSE_SUCCESS = "UPDATE_EXPENSE_SUCCESS";
export const UPDATE_EXPENSE_FAILED = "UPDATE_EXPENSE_FAILED";

export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCES";
export const FETCH_SCHEDULE_FAILED = "FETCH_SCHEDULE_FAILED";
export const ADD_SCHEDULE_SUCCESS = "ADD_SCHEDULE_SUCCESS";
export const ADD_SCHEDULE_FAILED = "ADD_SCHEDULE_FAILED";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAILED = "DELETE_SCHEDULE_FAILED";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILED = "UPDATE_SCHEDULE_FAILED";


